{% set name = "libsemigroups" %}
{% set version = "1.0.0" %}
{% set sha256 = "db58bddf29ef58b4caeba42fa7cf5e1b52406c6b5c5c6c23c7e9d571b3f3de48" %}
{% set repo = "https://github.com/libsemigroups/libsemigroups" %}
{% set home = "https://libsemigroups.github.io/libsemigroups/" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: {{ repo }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - test -d ${PREFIX}/include/libsemigroups                    # [unix]
    - test -f ${PREFIX}/include/libsemigroups/libsemigroups.hpp  # [unix]
    - test -f $PREFIX/lib/libsemigroups.dylib                    # [osx]
    - test -f $PREFIX/lib/libsemigroups.so                       # [linux]
    - test -f $PREFIX/lib/libsemigroups.a                        # [unix]

    - if exist %LIBRARY_PREFIX%\include\libsemigroups\libsemigroups.hpp (exit 0) else (exit 1)  # [win]

about:
  home: {{ home }}
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'C++ library for semigroups and monoids'

  description: |
    libsemigroups is a C++ library for semigroups and monoids.
  doc_url: {{ home }}
  dev_url: {{ repo }}

extra:
  recipe-maintainers:
    - james-d-mitchell
    - nthiery
