{% set name = "libsemigroups" %}
{% set version = "1.0.5" %}
{% set sha256 = "00ab929c49866e12b18e61309a6f8f3bcdb1c9a59f1c30a8a8e8a8da4065dd8a" %}
{% set repo = "https://github.com/libsemigroups/libsemigroups" %}
{% set home = "https://libsemigroups.github.io/libsemigroups/" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: {{ repo }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("libsemigroups", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - automake
    - autoconf
    - libtool
  host: []
  run: []

test:
  commands:
    - test -d ${PREFIX}/include/libsemigroups                    # [unix]
    - test -f ${PREFIX}/include/libsemigroups/libsemigroups.hpp  # [unix]
    - test -f $PREFIX/lib/libsemigroups.dylib                    # [osx]
    - test -f $PREFIX/lib/libsemigroups.so                       # [linux]
    - test -f $PREFIX/lib/libsemigroups.a                        # [unix]

    - if exist %LIBRARY_PREFIX%\include\libsemigroups\libsemigroups.hpp (exit 0) else (exit 1)  # [win]

about:
  home: {{ home }}
  license: GPL-3.0
  license_file: LICENSE
  summary: 'C++ library for semigroups and monoids'

  description: |
    libsemigroups is a C++ library for semigroups and monoids.
  doc_url: {{ home }}
  dev_url: {{ repo }}

extra:
  recipe-maintainers:
    - james-d-mitchell
    - nthiery
