{% set name = "libsemigroups" %}
<<<<<<< HEAD
{% set version = "0.6.7" %}
{% set sha256 = "635ac5ef9251b22092028d6a28ce0493fff3ec7c0dc39a8600d90c8371db3a6c" %}
{% set repo = "https://github.com/libsemigroups/libsemigroups" %}
{% set home = "https://james-d-mitchell.github.io/libsemigroups/" %}
=======
{% set version = "1.0.3" %}
{% set sha256 = "6adc2e023ad1349f0a942355b88241198d23790e62216bfeb62c356d803119da" %}
{% set repo = "https://github.com/libsemigroups/libsemigroups" %}
{% set home = "https://libsemigroups.github.io/libsemigroups/" %}
>>>>>>> master

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: {{ repo }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
<<<<<<< HEAD
    - make
    - automake
    - autoconf
    - libtool
  host:
=======
  host: []
  run: []
>>>>>>> master

test:
  commands:
    - test -d ${PREFIX}/include/libsemigroups                    # [unix]
    - test -f ${PREFIX}/include/libsemigroups/libsemigroups.hpp  # [unix]
    - test -f $PREFIX/lib/libsemigroups.dylib                    # [osx]
    - test -f $PREFIX/lib/libsemigroups.so                       # [linux]
    - test -f $PREFIX/lib/libsemigroups.a                        # [unix]

    - if exist %LIBRARY_PREFIX%\include\libsemigroups\libsemigroups.hpp (exit 0) else (exit 1)  # [win]

about:
  home: {{ home }}
  license: GPL-3.0
  license_file: LICENSE
  summary: 'C++ library for semigroups and monoids'

  description: |
    libsemigroups is a C++ library for semigroups and monoids.
  doc_url: {{ home }}
  dev_url: {{ repo }}

extra:
  recipe-maintainers:
    - james-d-mitchell
    - nthiery
