{% set name = "libsemigroups" %}
{% set version = "3.2.0" %}
{% set sha256 = "dee76bfa566410342422346d9ae94fffc03b35b3e8b7415a558cab456338c077" %}
{% set repo = "https://github.com/libsemigroups/libsemigroups" %}
{% set home = "https://libsemigroups.github.io/libsemigroups/" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: {{ repo }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("libsemigroups", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
    - automake
    - autoconf
    - libtool
    - pkg-config
  host:
    - fmt
    - eigen
    - backward-cpp
  run:
    - {{ pin_compatible("fmt") }}
    - {{ pin_compatible("eigen") }}
    - {{ pin_compatible("backward-cpp") }}

test:
  commands:
    - test -d ${PREFIX}/include/libsemigroups                    # [unix]
    - test -f ${PREFIX}/include/libsemigroups/libsemigroups.hpp  # [unix]
    - test -f $PREFIX/lib/libsemigroups.dylib                    # [osx]
    - test -f $PREFIX/lib/libsemigroups.so                       # [linux]
    - test -f $PREFIX/lib/libsemigroups.a                        # [unix]

    - if exist %LIBRARY_PREFIX%\include\libsemigroups\libsemigroups.hpp (exit 0) else (exit 1)  # [win]

about:
  home: {{ home }}
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: C++ library for semigroups and monoids

  description: |
    libsemigroups is a C++ library for semigroups and monoids.
  doc_url: {{ home }}
  dev_url: {{ repo }}

extra:
  recipe-maintainers:
    - james-d-mitchell
    - nthiery
    - joseph-edwards
