# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "CYz8NVby9RBwjwleh/Yf2xbmjUBNEdc8pbH18sglmwkM0xDxfd/FyQ7aPEEdbtoiiusuwyaoY7AVG63lwR0xv4Anm6UhGbS5DNVdPM2/pgEp30OBhB5RQjMLPyWVhDzvA55pTb3foLkpCqgiRqY/82TS4c3Km1VzK/hcPhprof7UjDC++dSDGYIt8XIe/OTDtT/QbyXMqRtS1ujfdYN/OiGF+zuWDva844e3IdXyEOzXTTyeoBpWQrs7YFkssWICo0i8Wvd7dCgE8tZ+Y81NSzs8lg4aGJMQRIT9SnLjWlJFSt2CNdgVQOUl5agOcg46FB+gccHzWpsDWNzg+aY8DkF4n8k+ownVf0DvlpiT0tbGqhm/C7hdgNUMhdwMoqpfhaQ+4LVHIUHhF590W/B0bLetRD1zhNERNpNTPHIY2vW6bpw2GZSbwFqUgj5ZFvKfh7gy9wq45tCoVzww75/YgOqudDTc5D5VmXA3F4PaueiGazxfJo19mh/q1v5/t2JvcQE2TF26Gkt2WcM8uHezZCszjHfxxpUyhGWB+MovLpKHjqZMO7g9SVTZIv22mOXLLEr6V1tM8Q73Rv15A0GucsGBen94rEfLaeijuYQR7k+fmBhwe00PoQ40NcaoSafJUaO5UjKEtzpLFCH1CZR9nAAMs5xN7xtbqV48ttvLfio="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_ UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"
  - export FEEDSTOCK_NAME=$(basename ${TRAVIS_REPO_SLUG})


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi