appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider:
  osx: azure
  linux: azure
travis:
  secure: {BINSTAR_TOKEN: CYz8NVby9RBwjwleh/Yf2xbmjUBNEdc8pbH18sglmwkM0xDxfd/FyQ7aPEEdbtoiiusuwyaoY7AVG63lwR0xv4Anm6UhGbS5DNVdPM2/pgEp30OBhB5RQjMLPyWVhDzvA55pTb3foLkpCqgiRqY/82TS4c3Km1VzK/hcPhprof7UjDC++dSDGYIt8XIe/OTDtT/QbyXMqRtS1ujfdYN/OiGF+zuWDva844e3IdXyEOzXTTyeoBpWQrs7YFkssWICo0i8Wvd7dCgE8tZ+Y81NSzs8lg4aGJMQRIT9SnLjWlJFSt2CNdgVQOUl5agOcg46FB+gccHzWpsDWNzg+aY8DkF4n8k+ownVf0DvlpiT0tbGqhm/C7hdgNUMhdwMoqpfhaQ+4LVHIUHhF590W/B0bLetRD1zhNERNpNTPHIY2vW6bpw2GZSbwFqUgj5ZFvKfh7gy9wq45tCoVzww75/YgOqudDTc5D5VmXA3F4PaueiGazxfJo19mh/q1v5/t2JvcQE2TF26Gkt2WcM8uHezZCszjHfxxpUyhGWB+MovLpKHjqZMO7g9SVTZIv22mOXLLEr6V1tM8Q73Rv15A0GucsGBen94rEfLaeijuYQR7k+fmBhwe00PoQ40NcaoSafJUaO5UjKEtzpLFCH1CZR9nAAMs5xN7xtbqV48ttvLfio=}
